<?php
	/* generated by 'install.php' Thu, 07 Nov 2019 19:01:51 +0100 */
	$mysql_host 	= 'localhost';
	$mysql_db 		= 'main';
	$mysql_user 	= 'MAINROOT';
	$mysql_passwd 	= 'Andrew171165';
	$mysql_prefix 	= '';
?>